### ISSUE TITLE
sql errors in the logs

### ISSUE THREAD

**Issue by bastianh** [ScreepsMods/screepsmod-history#16]
I see a lot of sql errors in the logs .. it's working so maybe there are duplicate saves?

I also deleted the database and restartet the server, does not change the spam .)

```
[historyWorker] Error processing room E31N3@53440 { SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/screeps/node_modules/sequelize/lib/dialects/sqlite/query.js:409:16)
    at Query._handleQueryResponse (/screeps/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at Statement.afterExecute (/screeps/node_modules/sequelize/lib/dialects/sqlite/query.js:246:27)
  name: 'SequelizeUniqueConstraintError',
  errors:
   [ ValidationErrorItem {
       message: 'room must be unique',
       type: 'unique violation',
       path: 'room',
       value: 'E31N3',
       origin: 'DB',
       instance: [history],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] },
     ValidationErrorItem {
       message: 'tick must be unique',
       type: 'unique violation',
       path: 'tick',
       value: 53440,
       origin: 'DB',
       instance: [history],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: [ 'room', 'tick' ],
  parent:
   { Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: histories.room, histories.tick
     errno: 19,
     code: 'SQLITE_CONSTRAINT',
     sql:
      'INSERT INTO `histories` (`id`,`room`,`tick`,`data`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2,$3,$4,$5);' },
  original:
   { Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: histories.room, histories.tick
     errno: 19,
     code: 'SQLITE_CONSTRAINT',
     sql:
      'INSERT INTO `histories` (`id`,`room`,`tick`,`data`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2,$3,$4,$5);' },
  sql:
   'INSERT INTO `histories` (`id`,`room`,`tick`,`data`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2,$3,$4,$5);' }
```

**Comment by pieterbrandsen** [comment]
The error is indeed that there is already a row with that combo in the db, so there is an duplicate being uploaded
